# ===================== COMMON (applies to all profiles) =====================
spring:
  application:
    name: cabBooking
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090

# JWT & SMS: read from env in prod; dev overrides below
jwt:
  secret: ${JWT_SECRET:change-me-in-prod}
  expirationMs: ${JWT_EXPIRATION_MS:8600000}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:604800000}

fast2sms:
  api:
    key: ${FAST2SMS_API_KEY:dev-fast2sms-key}
  route: ${FAST2SMS_ROUTE:otp}
  flash: ${FAST2SMS_FLASH:0}
  base:
    url: ${FAST2SMS_BASE_URL:https://www.fast2sms.com/dev/bulkV2}

# ===================== DEV PROFILE (your localhost in IntelliJ) =============
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chalocab_db?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update      # OK for dev
    show-sql: true

# If you need to expose on LAN in dev, uncomment:
# server:
#   address: 0.0.0.0

# Keep your current dev secrets here (works out-of-the-box locally).
# Rotate before pushing to public repos.
jwt:
  secret: chaloCabSuperSecretKey1234567890AB
  expirationMs: 8600000
  refreshExpirationMs: 604800000

fast2sms:
  api:
    key: uBr29QVwTDYNXaIAySbvkcqLPEgJMi3zGnmWoHO0l5eKdpFxhUqnWmY7ohAP8zbpFtxlX9c3fkuyZT1M
  route: otp
  flash: 0
  base:
    url: https://www.fast2sms.com/dev/bulkV2

# ===================== PROD PROFILE (AWS/RDS) ================================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Read from env in Jenkins/EC2 (recommended)
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    # Or, if you insist on hardcoding, comment the 3 lines above and uncomment:
    # url: jdbc:mysql://chalocabdb.clyy88wwkchq.ap-south-1.rds.amazonaws.com:3306/chalocab_db
    # username: admin
    # password: rootadmin
  jpa:
    hibernate:
      ddl-auto: update     # NEVER change schema in prod automatically
    show-sql: false

# Flyway will be added later; leaving out here to keep step 1 focused.
# When ready, you'll enable it only in prod like:
# spring:
#   flyway:
#     enabled: true
#     locations: classpath:db/migration

# JWT & SMS: must come from env in prod
jwt:
  secret: ${JWT_SECRET}                # e.g. set in Jenkins/EC2
  expirationMs: ${JWT_EXPIRATION_MS:8600000}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:604800000}

fast2sms:
  api:
    key: ${FAST2SMS_API_KEY}
  route: ${FAST2SMS_ROUTE:otp}
  flash: ${FAST2SMS_FLASH:0}
  base:
    url: ${FAST2SMS_BASE_URL:https://www.fast2sms.com/dev/bulkV2}
